In [15]:
import pandas as pd
import numpy as np
from dateutil.parser import parse
import math

In [16]:
######## Global Variables ##############
null_count = 0

true_date=0
false_date=0
nan_count_date = 0

true_numeric=0
false_numeric=0
nan_count_numeric=0

true_text=0
false_text=0
nan_count_text=0

numeric_ex = []
datetime_ex = []
text_ex = []
string_ex = []

## Algorithm

isNumeric()<br>
&nbsp;&nbsp;&nbsp;&nbsp;isNumericCount (T)-> count( numeric) <br>
&nbsp;&nbsp;&nbsp;&nbsp;notNumericCount (F)-> count(not numeric) <br>
&nbsp;&nbsp;&nbsp;&nbsp;F ==0 and T == 0 <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Empty column <br>
&nbsp;&nbsp;&nbsp;&nbsp;F==0 <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Numeric <br>
&nbsp;&nbsp;&nbsp;&nbsp;Else:	 <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;isDateTime() <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;isDateCount & notDateCount <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;If notDateCount == 0: <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Output datetype <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Else:	<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;isText() <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;textCount  <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;notTextCnt <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;If notTextCnt == 0: <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Text <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Else: <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;If isCategorical(): <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Categorical <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Else: <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;If  isDateCount> 0 or isNumericCount >0 or textCount > 0 : <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Mixed <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;String count + nan count = Total rows- (isDateCount+  isNumericCount+ textCount ) <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;nanCount = getNanCount() <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Now obtain stringCount <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Else: <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;String <br>

In [17]:
def is_nan(s):
    global null_count
    if isinstance(s,float) and np.isnan(s):
        null_count = null_count+1

def getNanCount(col):
    global null_count
    null_count=0
    col.apply(lambda x: is_nan(x))
    return null_count

In [18]:
def is_string(string):
    flag = 1
    if isinstance(string,float) and np.isnan(string):
        flag = 0
    else:
        try:
            float(string)
            flag = 0
        
        except ValueError:
            try:
                parse(string)
                flag = 0
            except ValueError:
                if len(string) > 50:
                    flag = 0
    return flag


def get_string_ex(col):
    global string_ex
    string_ex = []
    for val in col:
        if len(string_ex) == 101:
            break
        if is_string(val) and val not in string_ex:
            string_ex.append(val)
            
    return string_ex

get_string_ex(df['ResultCommentText'])

[u'Temp at lab - iced.',
 u'MATRIX DUPLICATE Q.C. EXCEEDED',
 u'HOLDING TIME EXCEEDED BY 26 DAYS',
 u'Assumed sample time was noon.',
 u'Analyzed past the 48 hours holding time.',
 u'RECEIVED PAST RECOMMENDED HOLDING TIME',
 u'HOLDING TIME EXCEEDED BY 2 DAYS',
 u'MATRIX DUPLICATE QC EXCEEDED.',
 u'DUP QC EXCEEDED, RESULT AVG OF 0.0041 & 0.0077',
 u'MATRIX DUPLICATE EXCEEDED',
 u'LOW SAMPLE VOLUME',
 u'NO BOTTLE RECEIVED, NO TEST DONE',
 u'LAB FORTIFIED BLANK EXCEEDS QC BY 1.2%',
 u'NO FILTER RECEIVED, NO TEST DONE',
 u'Lab sample temperature = -1 deg C.',
 u'Lab sample temperature = 5 deg C.',
 u'Lab sample temperature = 3 deg C.',
 u'Lab sample temperature = 1 deg C.',
 u'Lab sample temperature = 4 deg C.']

In [19]:
################# Function to check if the data type of a value is date ########################


def is_date(string):
    global true_date,false_date,nan_count_date,datetime_ex
    if isinstance(string,float) and np.isnan(string):
        nan_count_date = nan_count_date+1
        # do nothing
    else:
        try:
            float(string)
        #print (string)
            false_date=false_date+1
        except ValueError:
            try:
                parse(string)
                #print (string)
                true_date=true_date+1
                if(len(datetime_ex) < 100) and string not in datetime_ex:
                    datetime_ex.append(string)
            except ValueError:
                false_date=false_date+1
            
            
def is_date_column(col):
    global true_date,false_date,nan_count_date,datetime_ex
    true_date=0
    false_date=0
    nan_count_date = 0
    datetime_ex = []

    col.apply(lambda x: is_date(x))
    return true_date,false_date,datetime_ex
#     if true_date > 0 and false_date == 0:
#         return True
#     else:
#         return False
# true_date, false_date,nan_count_date
is_date_column(df['ActivityStartDate'])

(1799,
 0,
 [u'5/29/2002',
  u'6/17/2002',
  u'6/27/2002',
  u'7/7/2002',
  u'7/17/2002',
  u'5/15/2003',
  u'7/1/2003',
  u'7/31/2003',
  u'8/14/2003',
  u'6/19/2004',
  u'7/2/2004',
  u'8/29/2004',
  u'6/3/2005',
  u'7/6/2005',
  u'7/17/2005',
  u'7/21/2005',
  u'8/20/2005',
  u'11/2/2005',
  u'5/16/2006',
  u'6/18/2006',
  u'7/20/2006',
  u'8/28/2006',
  u'10/5/2006',
  u'6/14/2007',
  u'7/26/2007',
  u'8/29/2007',
  u'10/28/2007',
  u'9/5/2000',
  u'8/7/2001',
  u'5/30/2001',
  u'6/29/2001',
  u'7/27/2001',
  u'9/12/2001',
  u'11/7/2001',
  u'8/22/2008',
  u'8/29/2008',
  u'9/18/2008',
  u'10/14/2008',
  u'4/22/2009',
  u'6/1/2009',
  u'6/16/2009',
  u'7/13/2009',
  u'8/11/2009',
  u'9/8/2009',
  u'10/7/2009',
  u'4/20/2010',
  u'6/2/2010',
  u'6/15/2010',
  u'7/12/2010',
  u'8/10/2010',
  u'9/9/2010',
  u'10/5/2010',
  u'9/22/1992',
  u'2/3/1993',
  u'5/19/1993',
  u'8/16/1993',
  u'10/4/1993',
  u'1/24/1994',
  u'5/2/1994',
  u'5/3/1994',
  u'6/21/1994',
  u'8/3/1994',
  u'9/21/1994',
  u'7/14/2013',
  u'8/1/2013',
  u'8/13/2013',
  u'8/31/2013',
  u'8/1/2014',
  u'8/8/2014',
  u'8/16/2014',
  u'9/28/2014',
  u'8/13/2015',
  u'9/30/2015',
  u'7/26/2016',
  u'8/7/2016',
  u'8/31/2016',
  u'5/24/2017',
  u'5/26/2017',
  u'5/28/2017',
  u'5/30/2017',
  u'6/6/2017',
  u'6/15/2017',
  u'6/21/2017',
  u'6/29/2017',
  u'8/11/2017',
  u'6/17/1997',
  u'9/8/1997',
  u'10/20/1997',
  u'3/24/1998',
  u'9/10/2000',
  u'9/15/2000',
  u'9/17/2000',
  u'10/1/2000',
  u'5/22/2001',
  u'6/19/2001',
  u'5/4/2004',
  u'8/2/2004',
  u'6/12/2008',
  u'7/17/2008',
  u'8/19/2008'])

In [20]:
################# Function to check if the data type of a value is numeric ########################


def is_number(n):
    global true_numeric,false_numeric,nan_count_numeric,numeric_ex
    if (isinstance(n,float) and np.isnan(n)):
        nan_count_numeric=nan_count_numeric+1
    else:
        try:
            float(n)   # Type-casting the string to `float`.
                       # If string is not a valid `float`, 
                       # it'll raise `ValueError` exception
            #print ("num")
            if(len(numeric_ex) < 100) and n not in numeric_ex:
                numeric_ex.append(n)
            true_numeric=true_numeric+1
        except ValueError:
            #print ("not num")
            false_numeric=false_numeric+1
            
def get_numeric_stats(col):
    global true_numeric,false_numeric,nan_count_numeric,numeric_ex
    true_numeric=0
    false_numeric=0
    nan_count_numeric=0
    numeric_ex = []

    col.apply(lambda x: is_number(x))
    return true_numeric,false_numeric,numeric_ex

get_numeric_stats(df['NormalizedResultMeasureValue'])
# true_numeric, false_numeric,nan_count_numeric

(1795,
 4,
 [u'1.524',
  u'2.286',
  u'1.6764',
  u'2.5908',
  u'2.2098',
  u'1.8288',
  u'2.1336',
  u'2.3622',
  u'8.888888889',
  u'0',
  u'10',
  u'11',
  u'3',
  u'12.77777778',
  u'1',
  u'16.88888889',
  u'5',
  u'21.16666667',
  u'6',
  u'26',
  u'26.66666667',
  u'8',
  u'28.16666667',
  u'1.905',
  u'0.00339',
  u'0.031',
  u'23.88888889',
  u'22.77777778',
  u'4',
  u'21.66666667',
  u'17.77777778',
  u'15',
  u'9.444444444',
  u'1.9812',
  u'0.027',
  u'0.00591',
  u'0.00571',
  u'0.036',
  u'2.0574',
  u'9.555555556',
  u'11.16666667',
  u'11.5',
  u'11.66666667',
  u'12',
  u'12.5',
  u'14.38888889',
  u'14.55555556',
  u'0.023',
  u'0.004',
  u'9.777777778',
  u'10.55555556',
  u'13.27777778',
  u'18.55555556',
  u'23.38888889',
  u'23.77777778',
  u'2',
  u'0.00673',
  u'0.029',
  u'1.6002',
  u'10.38888889',
  u'15.5',
  u'20.16666667',
  u'24.5',
  u'25.05555556',
  u'25.77777778',
  u'0.034',
  u'0.0212',
  u'1.143',
  u'15.55555556',
  u'20',
  u'22.22222222',
  u'23.05555556',
  u'0.00765',
  u'0.022',
  u'12.88888889',
  u'13.38888889',
  u'17',
  u'18.66666667',
  u'21.05555556',
  u'24.77777778',
  u'25.38888889',
  u'25.66666667',
  u'0.00532',
  u'0.025',
  u'13',
  u'15.16666667',
  u'21.38888889',
  u'22.66666667',
  u'24.16666667',
  u'27.55555556',
  u'28.88888889',
  u'0.00779',
  u'1.0668',
  u'16.66666667',
  u'18.33333333',
  u'19.44444444',
  u'20.55555556',
  u'21.11111111',
  u'0.038',
  u'7.944444444'])

In [21]:
################# Function to check if the data type of a value is text ########################


def is_text(text):
    global true_text,false_text,nan_count_text,text_ex
    if (isinstance(text,float) and np.isnan(text)):
        nan_count_text=nan_count_text+1
    else:
        if (len(text) > 50):
            true_text=true_text+1
            if(len(text_ex) < 100) and text not in text_ex:
                text_ex.append(text)
            # return True
        else:
            false_text=false_text+1
            # return False
            
def is_text_column(col):
    global true_text,false_text,nan_count_text,text_ex
    true_text=0
    false_text=0
    nan_count_text=0
    text_ex = []

    col.apply(lambda x: is_text(x))
    return true_text,false_text,text_ex
#     if true_text>0 and false_text == 0:
#         return True
#     else:
#         return False

is_text_column(df['ResultCommentText'])

(18,
 414,
 [u'S. disc hit bottom. Please disregard TSI(SD).  Assumed sample time was noon.',
  u'Analyzed past the 28 days holding time: Method EPA 445 analyzed on 07/22/14 0000',
  u'Lab sample temperature = 11.5 deg C. which may be warmer than preservation protocol.  Lab remark:  Report Level was changed because the sample concentration exceeded the working range of the analysis.  Sample was diluted and reanalyzed.  Report Level was',
  u'Lab sample temperature = 11.5 deg C. which may be warmer than preservation protocol.',
  u'Lab sample temperature = 5 deg C. Lab remark:  Report Level was changed because the sample concentration exceeded the working range of the analysis.  Sample was diluted and reanalyzed.',
  u'Lab sample temperature = 11.6 deg C. which may be warmer than preservation protocol.',
  u'Lab sample temperature = 11 deg C. which may be warmer than preservation protocol.',
  u'Lab sample temperature = 1 deg C. Lab remark:  Holding time exceeded due to delayed sample delivery to the laboratory.',
  u'Lab sample temperature = 8 deg C. which may be warmer than preservation protocol.'])

In [22]:
################# Function to check if the data type of a value is categorical ########################

def is_categorical(col):
    length = len(col.unique())
#     if length > 1 and length < 5:
#         print (col.unique())
    return ( length > 1 and length < 5)
        
is_categorical(df['ResultCommentText'])

False

In [23]:
def profile_cols(df):
    datatypes = {}
    total_rows = len(df)
    for column in df:
        date_count,not_date_count,numeric_count, not_numeric_count,text_count,not_text_count,string_nan_count,nan_count=0,0,0,0,0,0,0,0
        dt = {}    
        numeric_count, not_numeric_count, numeric_ex = get_numeric_stats(df[column])
        if numeric_count == 0 and not_numeric_count == 0:
            dt["type"] = "None" 
        elif not_numeric_count == 0:
            dt["type"] = "Numeric"
        else:
            date_count,not_date_count, datetime_ex= is_date_column(df[column])
            if date_count > 0 and not_date_count == 0:
                dt["type"] = "DateTime" 
            else:
                text_count,not_text_count, text_ex = is_text_column(df[column])
                if text_count > 0 and not_text_count == 0:
                    dt["type"] = "Text"
                else:
                    if is_categorical(df[column]) :
                        dt["type"] = "Categorical"
                    else:
                        if date_count>0 or numeric_count >0 or text_count>0:
                            dt["type"] = "Mixed"
                            string_nan_count = total_rows - (date_count+numeric_count+text_count)
                            nan_count = getNanCount(df[column])
                            string_count = string_nan_count - nan_count
                            string_ex = get_string_ex(df[column])
                        
                            mixed_dt = {}
                            datetime_details = {}
                            numeric_details = {}
                            text_details = {}
                            string_details = {}
                            null_details = {}

                            datetime_details["count"] = date_count
                            datetime_details["examples"] = datetime_ex
                            numeric_details["count"] = numeric_count
                            numeric_details["examples"] = numeric_ex
                            text_details["count"] = text_count
                            text_details["examples"] = text_ex
                            string_details["count"] = string_count
                            string_details["examples"] = string_ex
                            null_details["count"] = nan_count

                            mixed_dt["datetime"] = datetime_details
                            mixed_dt["numeric"] = numeric_details
                            mixed_dt["text"] = text_details
                            mixed_dt["string"] = string_details
                            mixed_dt["null"] = null_details
                            
                            dt["details"] = mixed_dt
                        else:
                            dt["type"] = "String"
            datatypes[column] = dt
    return (datatypes)

In [24]:
def profile_cols_type(df, flag = 1):
    dtypes = profile_cols(df)
    return dtypes
#     sno = 1
#     for k,v in dtypes.items():
#         print (str(sno) + '. ' + k)
#         print ("\tDatatype:" + v)
#         if flag and v == "Mixed":
#             mixed_dt = mixed_dts[k]
#             print ("\tDistribution of datatypes:")
#             print ("\tDateTime:" + str(mixed_dt["datetime_count"] ))
#             print ("\tNumeric:" + str(mixed_dt["numeric_count"] ))
#             print ("\tText:" + str(mixed_dt["text_count"] ))
#             print ("\tString:" + str(mixed_dt["string_count"] ))
#             print ("\tNone:" + str(mixed_dt["null_count"] ))
#         print()
#         sno +=1

In [25]:
def print_cols_profile_summary(df, flag = 1, max_ex = 10):
    dtypes = profile_cols(df)
    if flag != 0 and flag !=1:
        print ("Flag value should be 0 or 1")
        return
    if max_ex < 1 or max_ex > 10:
        print("max_ex should be between 1 and 10")
        return
        
    sno = 1
    for k,v in dtypes.items():
        print (str(sno) + '. ' + k)
        type = v["type"]
        print ("\tDatatype: " + type)
        if flag == 1 and type == "Mixed":
            mixed_dt = v["details"]
            print ("\tDistribution of datatypes:")
            print()
            if mixed_dt["datetime"]["count"] != 0:
                print ("\tDatetime")
                print ("\tCount:" + str(mixed_dt["datetime"]["count"]))
                print ("\tExamples:")
                print_examples(mixed_dt["datetime"]["examples"], max_ex, 0)
                print()

            if mixed_dt["numeric"]["count"] != 0:
                print ("\tNumeric")
                print ("\tCount:" + str(mixed_dt["numeric"]["count"] ))
                print ("\tExamples:")
                print_examples(mixed_dt["numeric"]["examples"], max_ex, 0)
                print()

            if mixed_dt["text"]["count"] != 0:
                print ("\tText")
                print ("\tCount:" + str(mixed_dt["text"]["count"] ))
                print ("\tExamples:")
                print_examples(mixed_dt["text"]["examples"], max_ex, 0)
                print()

            if mixed_dt["string"]["count"] != 0:
                print ("\tString")
                print ("\tCount:" + str(mixed_dt["string"]["count"] ))
                print ("\tExamples:")
                print_examples(mixed_dt["string"]["examples"], max_ex, 0)
                print()

            if mixed_dt["null"]["count"] != 0:
                print ("\tNone")
                print ("\tCount:" + str(mixed_dt["null"]["count"] ))
                print()
                        
        print()
        print()
        sno +=1

In [26]:
def profile_single_col(df,attr):
    datatype = ""
    total_rows = len(df)
    date_count,not_date_count,numeric_count, not_numeric_count,text_count,not_text_count,\
    string_nan_count,nan_count=0,0,0,0,0,0,0,0
   
    numeric_count, not_numeric_count, numeric_ex = get_numeric_stats(df[attr])
    if numeric_count == 0 and not_numeric_count == 0:
        datatype = "None" 
    elif not_numeric_count == 0:
        datatype = "Numeric"
    else:
        date_count,not_date_count,datetime_ex = is_date_column(df[attr])
        if date_count > 0 and not_date_count == 0:
            datatype = "DateTime" 
        else:
            text_count,not_text_count,text_ex = is_text_column(df[attr])
            if text_count > 0 and not_text_count == 0:
                datatype = "Text"
            else:
                if is_categorical(df[attr]) :
                    datatype = "Categorical"
                else:
                    if date_count>0 or numeric_count >0 or text_count>0:
                        datatype = "Mixed"
                       
                        string_nan_count = total_rows - (date_count+numeric_count+text_count)
                        
                        nan_count = getNanCount(df[attr])
                        string_count = string_nan_count - nan_count
                        string_ex = get_string_ex(df[attr])
                        
                        mixed_dt = {}
                        datetime_details = {}
                        numeric_details = {}
                        text_details = {}
                        string_details = {}
                        null_details = {}
                        
                        datetime_details["count"] = date_count
                        datetime_details["examples"] = datetime_ex
                        numeric_details["count"] = numeric_count
                        numeric_details["examples"] = numeric_ex
                        text_details["count"] = text_count
                        text_details["examples"] = text_ex
                        string_details["count"] = string_count
                        string_details["examples"] = string_ex
                        null_details["count"] = nan_count
                        
                        mixed_dt["datetime"] = datetime_details
                        mixed_dt["numeric"] = numeric_details
                        mixed_dt["text"] = text_details
                        mixed_dt["string"] = string_details
                        mixed_dt["null"] = null_details
                        
                    else:
                        datatype = "String"
    return (datatype,mixed_dt)

In [27]:
def profile_col_type(df, attr, flag = 1):
    dt, mixed_dt = profile_single_col(df,attr)
    if flag == 1:
        return dt, mixed_dt
    elif flag == 0:
        return dt
    else:
        return "Flag value should be 0 or 1"

In [28]:
def print_examples(ex, n, flag = 1):
    count = 0
    for i in range(len(ex)):
        if count == n:
            break
        if flag:
            print (ex[i])
        else:
            print("\t" + str(ex[i]))
            
        count += 1
        
    print()

In [31]:
def print_col_profile_summary(df, attr, flag = 1, max_ex = 100):
    dt, mixed_dt = profile_single_col(df,attr)
    print ("Attribute: " + attr)
    print ("Datatype: " + dt)
    print()
    if flag == 1:
        if dt == "Mixed":
            if max_ex < 1 or max_ex > 100:
                print("max_ex should be between 1 and 100")
            else:
                print ("Distribution of datatypes:")
                print()
                if mixed_dt["datetime"]["count"] != 0:
                    print ("Datetime")
                    print ("Count:" + str(mixed_dt["datetime"]["count"]))
                    print ("Examples:")
                    print_examples(mixed_dt["datetime"]["examples"], max_ex)
                    print()
                
                if mixed_dt["numeric"]["count"] != 0:
                    print ("Numeric")
                    print ("Count:" + str(mixed_dt["numeric"]["count"] ))
                    print ("Examples:")
                    print_examples(mixed_dt["numeric"]["examples"], max_ex)
                    print()
                
                if mixed_dt["text"]["count"] != 0:
                    print ("Text")
                    print ("Count:" + str(mixed_dt["text"]["count"] ))
                    print ("Examples:")
                    print_examples(mixed_dt["text"]["examples"], max_ex)
                    print()
                
                if mixed_dt["string"]["count"] != 0:
                    print ("String")
                    print ("Count:" + str(mixed_dt["string"]["count"] ))
                    print ("Examples:")
                    print_examples(mixed_dt["string"]["examples"], max_ex)
                    print()
                
                if mixed_dt["null"]["count"] != 0:
                    print ("None")
                    print ("Count:" + str(mixed_dt["null"]["count"] ))
                    print()
                           
    else:
        if flag!=0:
            print ("Flag value should be 0 or 1")

In [32]:
file_ = 'merged_data.csv'
df = pd.read_csv(file_, encoding='UTF-8')
del df['Unnamed: 0']
#
profile_col_type(df, 'ResultAnalyticalMethod/MethodName', 1)

('Mixed',
 {'datetime': {'count': 0, 'examples': []},
  'null': {'count': 966},
  'numeric': {'count': 0, 'examples': []},
  'string': {'count': 806,
   'examples': [u'In-Vitro Determination of Chlorophyll',
    u'Phosphorus by Colorimetry',
    u'MEASURED IN FIELD',
    u'Phosphorus by Single Reagent Colorimetry',
    u'Non-Filterable Residue - TSS',
    u'Field measurement/observation, generic method',
    u'Total Kjeldahl Nitrogen by Colorimetry',
    u'Total Phosphorus After Block Digestion',
    u'Chlorophyll-a and Pheophytin-a',
    u'Ammonia in Water Using Automated Phenate Method',
    u'Chlorophyll a-b-c Determination',
    u'Nitrate in Water- Automated Cadmium Reduction',
    u'pH',
    u'Ammonia Nitrogen by Colorimetry',
    u'Nitrate-Nitrite Nitrogen by Colorimetry',
    u'Turbidity in Water',
    u'Conductivity in Water',
    u'Alkalinity in Water by Titration',
    u'Total Suspended Solids in Water',
    u'Chloride by Colorimetric Analysis II',
    u'Phosphorus by Two Reagent Colorimetry']},
  'text': {'count': 27,
   'examples': [u'Phosphorus in Water by Colorimetry- Ascorbic Acid Method',
    u'Microcystins and Nodularins by Immunoassay, Microtiter Plate']}})

In [33]:
print_col_profile_summary(df, 'SampleCollectionMethod/MethodName', 1, 100)

Attribute: SampleCollectionMethod/MethodName
Datatype: Mixed
()
Distribution of datatypes:
()
Text
Count:144
Examples:
Grab sample.  Submerge and fill a water sampling vessel, or sample directly into the sample bottle provided by the an...
Lake surface 2m depth-integrated sampling. Lower a 2-meter-long, 2-inch-diameter PVC pipe vertically into the water, ...
()
()
String
Count:1655
Examples:
USEPA
WATER GRAB SAMPLE
IL_EPA
Sample-collection method not available
()
()

In [66]:
profile_cols_type(df)

{'Action': {'type': 'Categorical'},
 'ActivityBottomDepthHeightMeasure/MeasureUnitCode': {'type': 'Categorical'},
 'ActivityCommentText': {'type': 'Categorical'},
 'ActivityConductingOrganizationText': {'type': 'Categorical'},
 'ActivityDepthAltitudeReferencePointText': {'type': 'Categorical'},
 'ActivityDepthHeightMeasure/MeasureUnitCode': {'type': 'Categorical'},
 'ActivityEndDate': {'type': 'DateTime'},
 'ActivityEndTime/Time': {'type': 'DateTime'},
 'ActivityEndTime/TimeZoneCode': {'type': 'Categorical'},
 'ActivityIdentifier': {'type': 'String'},
 'ActivityMediaName': {'type': 'Categorical'},
 'ActivityMediaSubdivisionName': {'type': 'Categorical'},
 'ActivityStartDate': {'type': 'DateTime'},
 'ActivityStartTime/Time': {'type': 'DateTime'},
 'ActivityStartTime/TimeZoneCode': {'type': 'Categorical'},
 'ActivityTopDepthHeightMeasure/MeasureUnitCode': {'type': 'Categorical'},
 'ActivityTypeCode': {'type': 'Categorical'},
 'AnalysisStartDate': {'type': 'DateTime'},
 'CharacteristicName': {'type': 'String'},
 'DetectionQuantitationLimitMeasure/MeasureUnitCode': {'type': 'Categorical'},
 'DetectionQuantitationLimitTypeName': {'type': 'Categorical'},
 'Function': {'type': 'Text'},
 'LaboratoryName': {'details': {'datetime': {'count': 0, 'examples': []},
   'null': {'count': 1307},
   'numeric': {'count': 262, 'examples': ['113133790']},
   'string': {'count': 230,
    'examples': ['Test America Chicago',
     'MN00025',
     'MN00006',
     'MN00037',
     'MN00059']},
   'text': {'count': 0, 'examples': []}},
  'type': 'Mixed'},
 'MeasureQualifierCode': {'type': 'Categorical'},
 'MethodDescriptionText': {'type': 'String'},
 'MonitoringLocationIdentifier': {'type': 'String'},
 'NormalizedCharacteristicName': {'type': 'String'},
 'NormalizedResultMeasure/MeasureUnitCode': {'type': 'String'},
 'NormalizedResultMeasureValue': {'details': {'datetime': {'count': 0,
    'examples': []},
   'null': {'count': 0},
   'numeric': {'count': 1795,
    'examples': ['1.524',
     '2.286',
     '1.6764',
     '2.5908',
     '2.2098',
     '1.8288',
     '2.1336',
     '2.3622',
     '8.888888889',
     '0',
     '10',
     '11',
     '3',
     '12.77777778',
     '1',
     '16.88888889',
     '5',
     '21.16666667',
     '6',
     '26',
     '26.66666667',
     '8',
     '28.16666667',
     '1.905',
     '0.00339',
     '0.031',
     '23.88888889',
     '22.77777778',
     '4',
     '21.66666667',
     '17.77777778',
     '15',
     '9.444444444',
     '1.9812',
     '0.027',
     '0.00591',
     '0.00571',
     '0.036',
     '2.0574',
     '9.555555556',
     '11.16666667',
     '11.5',
     '11.66666667',
     '12',
     '12.5',
     '14.38888889',
     '14.55555556',
     '0.023',
     '0.004',
     '9.777777778',
     '10.55555556',
     '13.27777778',
     '18.55555556',
     '23.38888889',
     '23.77777778',
     '2',
     '0.00673',
     '0.029',
     '1.6002',
     '10.38888889',
     '15.5',
     '20.16666667',
     '24.5',
     '25.05555556',
     '25.77777778',
     '0.034',
     '0.0212',
     '1.143',
     '15.55555556',
     '20',
     '22.22222222',
     '23.05555556',
     '0.00765',
     '0.022',
     '12.88888889',
     '13.38888889',
     '17',
     '18.66666667',
     '21.05555556',
     '24.77777778',
     '25.38888889',
     '25.66666667',
     '0.00532',
     '0.025',
     '13',
     '15.16666667',
     '21.38888889',
     '22.66666667',
     '24.16666667',
     '27.55555556',
     '28.88888889',
     '0.00779',
     '1.0668',
     '16.66666667',
     '18.33333333',
     '19.44444444',
     '20.55555556',
     '21.11111111',
     '0.038',
     '7.944444444']},
   'string': {'count': 4, 'examples': ['10.3F', '10.5F', '7.8FT', '*7.8']},
   'text': {'count': 0, 'examples': []}},
  'type': 'Mixed'},
 'Notes': {'type': 'Categorical'},
 'OrganizationFormalName': {'type': 'Categorical'},
 'OrganizationIdentifier': {'type': 'Categorical'},
 'ProjectIdentifier': {'type': 'String'},
 'ProviderName': {'type': 'String'},
 'ResultAnalyticalMethod/MethodIdentifier': {'details': {'datetime': {'count': 0,
    'examples': []},
   'null': {'count': 664},
   'numeric': {'count': 281,
    'examples': ['445',
     '365.1',
     '365.2',
     '160.2',
     '351.2',
     '365.4',
     '150.1',
     '350.1',
     '353.2',
     '2130',
     '2510',
     '520011',
     '2320',
     '325.2',
     '365.3']},
   'string': {'count': 854,
    'examples': ['FIELD',
     'LAB',
     'FLD',
     'ASTM D3731-87',
     '4500-NH3(G)',
     '4500-P-E',
     '10200-H',
     '4500-NO3(F)',
     '2540-D']},
   'text': {'count': 0, 'examples': []}},
  'type': 'Mixed'},
 'ResultAnalyticalMethod/MethodIdentifierContext': {'type': 'String'},
 'ResultAnalyticalMethod/MethodName': {'details': {'datetime': {'count': 0,
    'examples': []},
   'null': {'count': 966},
   'numeric': {'count': 0, 'examples': []},
   'string': {'count': 806,
    'examples': ['In-Vitro Determination of Chlorophyll',
     'Phosphorus by Colorimetry',
     'MEASURED IN FIELD',
     'Phosphorus by Single Reagent Colorimetry',
     'Non-Filterable Residue - TSS',
     'Field measurement/observation, generic method',
     'Total Kjeldahl Nitrogen by Colorimetry',
     'Total Phosphorus After Block Digestion',
     'Chlorophyll-a and Pheophytin-a',
     'Ammonia in Water Using Automated Phenate Method',
     'Chlorophyll a-b-c Determination',
     'Nitrate in Water- Automated Cadmium Reduction',
     'pH',
     'Ammonia Nitrogen by Colorimetry',
     'Nitrate-Nitrite Nitrogen by Colorimetry',
     'Turbidity in Water',
     'Conductivity in Water',
     'Alkalinity in Water by Titration',
     'Total Suspended Solids in Water',
     'Chloride by Colorimetric Analysis II',
     'Phosphorus by Two Reagent Colorimetry']},
   'text': {'count': 27,
    'examples': ['Phosphorus in Water by Colorimetry- Ascorbic Acid Method',
     'Microcystins and Nodularins by Immunoassay, Microtiter Plate']}},
  'type': 'Mixed'},
 'ResultCommentText': {'details': {'datetime': {'count': 0, 'examples': []},
   'null': {'count': 1367},
   'numeric': {'count': 302,
    'examples': ['5',
     '12',
     '210',
     '2.16',
     '8.32',
     '1',
     '3',
     '2.1',
     '0.976',
     '0.625',
     '38',
     '29.2',
     '150',
     '2',
     '126',
     '131',
     '205',
     '2.42',
     '19',
     '4.6',
     '0',
     '7.68',
     '1.31',
     '1.54',
     '26.3',
     '11',
     '9.95',
     '348',
     '69.2',
     '72.5',
     '200',
     '1.146',
     '45',
     '2.4',
     '220',
     '10',
     '7.64',
     '0.798',
     '42',
     '1.11',
     '250',
     '28',
     '1.35',
     '7.33',
     '6.1',
     '0.731',
     '35',
     '1.273',
     '3.4',
     '230',
     '22.9',
     '7.94',
     '2.5',
     '14',
     '2.71',
     '0.929',
     '30',
     '45.4',
     '40.4',
     '93.5',
     '9.83',
     '100',
     '7.6',
     '215',
     '3.1',
     '2.02',
     '8',
     '0.886',
     '80',
     '57.5',
     '1.476',
     '7.56',
     '50',
     '125',
     '5.4',
     '2.61',
     '1.072',
     '1.51',
     '1.66',
     '7.7',
     '9',
     '7.22',
     '21',
     '4.78',
     '6.64',
     '190',
     '17',
     '265',
     '7.47',
     '0.55',
     '15',
     '0.02',
     '0.04',
     '0.009',
     '0.07',
     '275',
     '8.07',
     '0.01',
     '0.71',
     '37']},
   'string': {'count': 112,
    'examples': ['Temp at lab - iced.',
     'MATRIX DUPLICATE Q.C. EXCEEDED',
     'HOLDING TIME EXCEEDED BY 26 DAYS',
     'Assumed sample time was noon.',
     'Analyzed past the 48 hours holding time.',
     'RECEIVED PAST RECOMMENDED HOLDING TIME',
     'HOLDING TIME EXCEEDED BY 2 DAYS',
     'MATRIX DUPLICATE QC EXCEEDED.',
     'DUP QC EXCEEDED, RESULT AVG OF 0.0041 & 0.0077',
     'MATRIX DUPLICATE EXCEEDED',
     'LOW SAMPLE VOLUME',
     'NO BOTTLE RECEIVED, NO TEST DONE',
     'LAB FORTIFIED BLANK EXCEEDS QC BY 1.2%',
     'NO FILTER RECEIVED, NO TEST DONE',
     'Lab sample temperature = -1 deg C.',
     'Lab sample temperature = 5 deg C.',
     'Lab sample temperature = 3 deg C.',
     'Lab sample temperature = 1 deg C.',
     'Lab sample temperature = 4 deg C.']},
   'text': {'count': 18,
    'examples': ['S. disc hit bottom. Please disregard TSI(SD).  Assumed sample time was noon.',
     'Analyzed past the 28 days holding time: Method EPA 445 analyzed on 07/22/14 0000',
     'Lab sample temperature = 11.5 deg C. which may be warmer than preservation protocol.  Lab remark:  Report Level was changed because the sample concentration exceeded the working range of the analysis.  Sample was diluted and reanalyzed.  Report Level was',
     'Lab sample temperature = 11.5 deg C. which may be warmer than preservation protocol.',
     'Lab sample temperature = 5 deg C. Lab remark:  Report Level was changed because the sample concentration exceeded the working range of the analysis.  Sample was diluted and reanalyzed.',
     'Lab sample temperature = 11.6 deg C. which may be warmer than preservation protocol.',
     'Lab sample temperature = 11 deg C. which may be warmer than preservation protocol.',
     'Lab sample temperature = 1 deg C. Lab remark:  Holding time exceeded due to delayed sample delivery to the laboratory.',
     'Lab sample temperature = 8 deg C. which may be warmer than preservation protocol.']}},
  'type': 'Mixed'},
 'ResultDepthHeightMeasure/MeasureUnitCode': {'type': 'Categorical'},
 'ResultLaboratoryCommentText': {'type': 'Text'},
 'ResultMeasure/MeasureUnitCode': {'type': 'String'},
 'ResultMeasureValue': {'details': {'datetime': {'count': 0, 'examples': []},
   'null': {'count': 0},
   'numeric': {'count': 1727,
    'examples': ['5',
     '7.5',
     '5.5',
     '8.5',
     '7.25',
     '6',
     '7',
     '7.75',
     '48',
     '0',
     '50',
     '51.8',
     '3',
     '55',
     '1',
     '62.4',
     '70.1',
     '78.8',
     '80',
     '8',
     '82.7',
     '6.25',
     '3.39',
     '0.031',
     '75',
     '73',
     '4',
     '71',
     '64',
     '59',
     '49',
     '6.5',
     '0.027',
     '5.91',
     '5.71',
     '0.036',
     '6.75',
     '49.2',
     '52.1',
     '52.7',
     '53',
     '53.6',
     '54.5',
     '57.9',
     '58.2',
     '0.023',
     '49.6',
     '51',
     '55.9',
     '65.4',
     '74.1',
     '74.8',
     '2',
     '6.73',
     '0.029',
     '5.25',
     '50.7',
     '59.9',
     '68.3',
     '76.1',
     '77.1',
     '78.4',
     '0.034',
     '21.2',
     '3.75',
     '60',
     '68',
     '72',
     '73.5',
     '7.65',
     '0.022',
     '55.2',
     '56.1',
     '10',
     '62.6',
     '65.6',
     '69.9',
     '76.6',
     '77.7',
     '78.2',
     '5.32',
     '0.025',
     '55.4',
     '59.3',
     '70.5',
     '72.8',
     '75.5',
     '81.6',
     '84',
     '7.79',
     '3.5',
     '62',
     '65',
     '67',
     '69',
     '70',
     '0.038',
     '46.3',
     '47.3',
     '47.4']},
   'string': {'count': 72,
    'examples': ['*0.063',
     '*21.2',
     '*0.0020',
     'ND',
     '10.3F',
     '*0.0010',
     '<0.02',
     '*0.915',
     '10.5F',
     '7.8FT',
     '*0.726',
     '*0.61',
     '*0.70',
     '*0.0110',
     '*0.71',
     '*0.76',
     '15.7 AT 24',
     '*7.8',
     '*0.036',
     '*0.02',
     '*0.006',
     '*0.004',
     '*<4',
     '**',
     '*ND']},
   'text': {'count': 0, 'examples': []}},
  'type': 'Mixed'},
 'ResultSampleFractionText': {'type': 'String'},
 'ResultStatusIdentifier': {'type': 'Categorical'},
 'ResultTemperatureBasisText': {'type': 'Categorical'},
 'ResultTimeBasisText': {'type': 'Categorical'},
 'ResultValueTypeName': {'type': 'Categorical'},
 'ResultWeightBasisText': {'type': 'Categorical'},
 'SampleCollectionEquipmentName': {'type': 'String'},
 'SampleCollectionMethod/MethodIdentifier': {'type': 'String'},
 'SampleCollectionMethod/MethodIdentifierContext': {'type': 'String'},
 'SampleCollectionMethod/MethodName': {'details': {'datetime': {'count': 0,
    'examples': []},
   'null': {'count': 0},
   'numeric': {'count': 0, 'examples': []},
   'string': {'count': 1655,
    'examples': ['USEPA',
     'WATER GRAB SAMPLE',
     'IL_EPA    ',
     'Sample-collection method not available']},
   'text': {'count': 144,
    'examples': ['Grab sample.  Submerge and fill a water sampling vessel, or sample directly into the sample bottle provided by the an...',
     'Lake surface 2m depth-integrated sampling. Lower a 2-meter-long, 2-inch-diameter PVC pipe vertically into the water, ...']}},
  'type': 'Mixed'},
 'Standard unit': {'type': 'String'},
 'StatisticalBaseCode': {'type': 'Categorical'},
 'Transformation': {'type': 'String'}}

In [75]:
print_cols_profile_summary(df, 0, 10)

1. OrganizationIdentifier
	Datatype: Categorical


2. OrganizationFormalName
	Datatype: Categorical


3. ActivityIdentifier
	Datatype: String


4. ActivityTypeCode
	Datatype: Categorical


5. ActivityMediaName
	Datatype: Categorical


6. ActivityMediaSubdivisionName
	Datatype: Categorical


7. ActivityStartDate
	Datatype: DateTime


8. ActivityStartTime/Time
	Datatype: DateTime


9. ActivityStartTime/TimeZoneCode
	Datatype: Categorical


10. ActivityEndDate
	Datatype: DateTime


11. ActivityEndTime/Time
	Datatype: DateTime


12. ActivityEndTime/TimeZoneCode
	Datatype: Categorical


13. ActivityDepthHeightMeasure/MeasureUnitCode
	Datatype: Categorical


14. ActivityDepthAltitudeReferencePointText
	Datatype: Categorical


15. ActivityTopDepthHeightMeasure/MeasureUnitCode
	Datatype: Categorical


16. ActivityBottomDepthHeightMeasure/MeasureUnitCode
	Datatype: Categorical


17. ProjectIdentifier
	Datatype: String


18. ActivityConductingOrganizationText
	Datatype: Categorical


19. MonitoringLocationIdentifier
	Datatype: String


20. ActivityCommentText
	Datatype: Categorical


21. SampleCollectionMethod/MethodIdentifier
	Datatype: String


22. SampleCollectionMethod/MethodIdentifierContext
	Datatype: String


23. SampleCollectionMethod/MethodName
	Datatype: Mixed


24. SampleCollectionEquipmentName
	Datatype: String


25. CharacteristicName
	Datatype: String


26. ResultSampleFractionText
	Datatype: String


27. ResultMeasureValue
	Datatype: Mixed


28. ResultMeasure/MeasureUnitCode
	Datatype: String


29. MeasureQualifierCode
	Datatype: Categorical


30. ResultStatusIdentifier
	Datatype: Categorical


31. StatisticalBaseCode
	Datatype: Categorical


32. ResultValueTypeName
	Datatype: Categorical


33. ResultWeightBasisText
	Datatype: Categorical


34. ResultTimeBasisText
	Datatype: Categorical


35. ResultTemperatureBasisText
	Datatype: Categorical


36. ResultCommentText
	Datatype: Mixed


37. ResultDepthHeightMeasure/MeasureUnitCode
	Datatype: Categorical


38. ResultAnalyticalMethod/MethodIdentifier
	Datatype: Mixed


39. ResultAnalyticalMethod/MethodIdentifierContext
	Datatype: String


40. ResultAnalyticalMethod/MethodName
	Datatype: Mixed


41. MethodDescriptionText
	Datatype: String


42. LaboratoryName
	Datatype: Mixed


43. AnalysisStartDate
	Datatype: DateTime


44. ResultLaboratoryCommentText
	Datatype: Text


45. DetectionQuantitationLimitTypeName
	Datatype: Categorical


46. DetectionQuantitationLimitMeasure/MeasureUnitCode
	Datatype: Categorical


47. ProviderName
	Datatype: String


48. Standard unit
	Datatype: String


49. Transformation
	Datatype: String


50. Notes
	Datatype: Categorical


51. Action
	Datatype: Categorical


52. Function
	Datatype: Text


53. NormalizedResultMeasureValue
	Datatype: Mixed


54. NormalizedCharacteristicName
	Datatype: String


55. NormalizedResultMeasure/MeasureUnitCode
	Datatype: String